# Generated by Django 4.2.7 on 2024-04-15 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkFk', models.CharField(max_length=150, unique=True, verbose_name='Sk or Fk')),
                ('password', models.CharField(max_length=2550, verbose_name='Password')),
                ('Fio', models.CharField(max_length=400, verbose_name='Fio')),
                ('mail', models.CharField(max_length=150, verbose_name='Mail')),
                ('coach', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coach.coach', verbose_name='Coach')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Student_id')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users2',
                'db_table': 'users',
            },
        ),
    ]
