# Generated by Django 4.2.7 on 2024-04-15 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach', '0001_initial'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150, verbose_name='Location')),
                ('start_date', models.DateTimeField(verbose_name='Start time')),
                ('end_date', models.DateTimeField(verbose_name='End time')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.coach', verbose_name='Coach')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'db_table': 'lessons2',
            },
        ),
    ]
